[postgres]
host = "aws-1-sa-east-1.pooler.supabase.com"
port = 6543
dbname = "postgres"
user = "postgres.drorhwwmogftgasnvpow"
password = "BackkendPeewee123456" 
sslmode = "require" 
pool_mode = "transaction"