[postgres]
host = "aws-1-sa-east-1.pooler.supabase.com"
port = 5432
dbname = "postgres"
user = "postgres.drorhwwmogftgasnvpow"
password = "JhUWmFq7Vp7%2ACJ%2F" 
sslmode = "require" 
pool_mode = "session"